Update dockerfile_v5 to contain previous stuff.
Update Dockerfile_v5

Update Dockerfile_v5

Update fsdp.py

Update Dockerfile_v5

Update Dockerfile_v5

Update Dockerfile_v5

Update Dockerfile_v5

Update Dockerfile_v5

diff --git a/docker/Dockerfile_v5 b/docker/Dockerfile_v5
--- a/docker/Dockerfile_v5
+++ b/docker/Dockerfile_v5
@@ -3,27 +3,25 @@ FROM us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_tpuv
 
 USER root
 
-# Install tools.
+# doesnt work -- copy this vm's sources.list which has europe version.
+# COPY /etc/apt/sources.list /etc/apt/sources.list
+
+RUN sed -i 's/deb.debian.org/ftp.de.debian.org/g' /etc/apt/sources.list
+
 ENV DEBIAN_FRONTEND=noninteractive
-RUN apt-get update
-RUN apt-get install -y --no-install-recommends apt-utils
-RUN apt-get install -y --no-install-recommends curl
-RUN apt-get install -y --no-install-recommends wget
-RUN apt-get install -y --no-install-recommends git
-
-# Install libraries.
 ENV PIP_ROOT_USER_ACTION=ignore
+
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    apt-utils \
+    curl \
+    wget \
+    git \
+    vim \
+    && rm -rf /var/lib/apt/lists/*
+
+# Add retry mechanism for apt-get
+RUN echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries
+
 RUN python3 -m pip install --upgrade pip
-RUN pip install numpy==1.24.4
-RUN pip install sentencepiece==0.1.99
 
-# Install from source.
-# COPY . /workspace/gemma/
-# WORKDIR /workspace/gemma/
-# RUN pip install -e .
-
-RUN pip install torch~=2.3.0 torch_xla[tpu]~=2.3.0 torchvision -f https://storage.googleapis.com/libtpu-releases/index.html
-RUN pip install transformers==4.38.2 -U
-RUN pip install datasets==2.18.0
-RUN pip install trl==0.8.1 peft==0.10.0
-RUN pip install accelerate==0.28.0
+HEALTHCHECK CMD curl --fail http://localhost:8080 || exit 1
